### ISSUE TITLE
Inconsistent pwsid labels for data/rates_data/rates_nc.xlsx

### ISSUE THREAD

**Issue by smyng91** [NIEPS-Water-Program/water-affordability#3]
I noticed inconsistent pwsid labels for https://github.com/NIEPS-Water-Program/water-affordability/blob/e656a173d7b793d51ef6699fc17ad066fad65ef5/data/rates_data/rates_nc.xlsx when compared against others. Please verify.

**Comment by pattersonla** [comment]
Yes - NC pwsids are standardized in the r scripts. Some were not used because there were not spatial boundaries available, and/or they represent portions of water systems that have different rate structures but no unique pwsid.

**Comment by smyng91** [comment]
Understood. Thanks.
